### PR TITLE
GUI_update

### LINKED ISSUE #15: [UI] Data 업데이트 기능 모듈화
- [ ] Data 업데이트 기능 모듈화

### PR DESCRIPTION
**Pull request by jjooeun**

### CODE REVIEW

**Review by blackgetter — COMMENTED** [review]
good~

**Review by blackgetter — CHANGES_REQUESTED** [review]
conflict 났다고 합니다 ㅠㅠ

**Comment by jjooeun** [comment]
resolve conflict
check please

**Review by blackgetter — COMMENTED** [review]
ddd

**Pull request closed without merging**
